services:
    pagination.twig.extension.pagination:
        class: Dmishh\Bundle\PagerBundle\Twig\Extension\PagerExtension
        arguments:
            - @templating.helper.router
        tags:
            - { name: twig.extension }
