services:
    pagination.twig.extension.pagination:
        class: Dmishh\PagerBundle\Twig\Extension\PaginationExtension
        arguments:
            - @templating.helper.router
            - @translator
        tags:
            - { name: twig.extension }
